#!/bin/bash
set -e

cd $(dirname $0)/..

CMD=bin/rancher
if [ ! -x $CMD ]; then
    ./scripts/build
fi

echo Starting rancher server

rm -rf build/testdata
mkdir -p build/testdata
cd build/testdata
export KUBECONFIG=/root/.kube/config
exec ../../$CMD
